### ISSUE TITLE
dlh_goolemaps erzeugt mit Contao 3.2.17 internen Serverfehler bei aktivierten Positionspin

### ISSUE THREAD

**Issue by 31er** [delahaye/dlh_googlemaps#49]
Contao 3.2.17
dlh_googlemaps 2.0.9

Nach einem Update von Contao 3.2.16 auf 3.2.17 kommt es im FE zu einem internen Serverfehler, wenn eine Karte mit Positionspin aufgerufen wird.

Fehlermeldung:
Fatal error: Out of memory (allocated 32243712) (tried to allocate 65484 bytes) in /htdocs/system/modules/core/models/FilesModel.php on line 44

Fehler tritt bei drei unterschiedlichen Hostern auf mit 100, 120, und 128MB memory_limit.

Wird der Pin deaktiviert, funktioniert alles bestens.
Ein Downgrade auf Contao 3.2.16 beseitigt auch das Problem.

**Comment by tuxenberger** [comment]
Kann ich in selber Konfiguration 

Contao 3.2.17
dlh_googlemaps 2.0.9

reproduzieren. Sobald der Pin aktiv ist, erscheint im Frondend nur noch eine leere Seite.

**Comment by Fnarks** [comment]
Die leere Seite kann ich ebenfalls reproduzieren. 
Sobald ein Kartenelement hinzugefügt wird bleibt die Seite leer. 
Ohne Kartenelement funktioniert alles wie gewünscht

**Comment by StudioV19** [comment]
Bei mir das selbe Problem bei 2 unterschiedlichen Webseiten. Bei beiden trat das Problem nach dem Update auf Contao 3.2.17 auf.

**Comment by matejjurancic** [comment]
Auch bei mir. Weiter geht's leider nicht auf Deutsch :)

Additionally I got this error:
```
Fatal error: Maximum function nesting level of '100' reached, aborting! in /path/to/contao/system/modules/core/library/Contao/Validator.php on line 284
```

I believe the problem is caused by modified code in Contao core class *Contao\FilesModel* as of 3.2.17. It seems thatnow the code loops itself between these static functions: *Contao\FilesModel::findByPk()*, *Contao\FilesModel::findById()* and *Contao\Model::findOneBy()*. Whereas the problem in this extension I found in class *delahaye\googlemaps\Googlemap->getElementData()*. I've added these additional checks to fix the bug (form line 205 onwards):
```
if (!empty($arrElement['overlaySRC'])) {
    $objFile = \FilesModel::findByPk($arrElement['overlaySRC']);
    $arrElement['overlaySRC'] = $objFile->path;
}
if (!empty($arrElement['shadowSRC'])) {
    $objFile = \FilesModel::findByPk($arrElement['shadowSRC']);
    $arrElement['shadowSRC'] = $objFile->path;
}
```

And, yes, I don't have any custom markers set.

**Comment by shelvis** [comment]
+1

**Comment by 31er** [comment]
Mit Contao 3.2.18 gibt es keine Probleme mehr bei mir.
Pin funktioniert wieder bestens.
